obj-$(CONFIG_MVEBU_CLK_CORE) 	+= clk.o clk-core.o
obj-$(CONFIG_MVEBU_CLK_CPU) 	+= clk-cpu.o
obj-$(CONFIG_MVEBU_CLK_GATING) 	+= clk-gating-ctrl.o
ifeq ($(CONFIG_SYNO_LSP_ARMADA),y)
obj-$(CONFIG_MVEBU_CLK_COREDIV)	+= clk-corediv.o
endif
