#
# Makefile for the Intel network device drivers.
#

obj-$(CONFIG_E100) += e100.o
obj-$(CONFIG_E1000) += e1000/
obj-$(CONFIG_E1000E) += e1000e/
obj-$(CONFIG_E1000E_NEW) += e1000e_new/
obj-$(CONFIG_IGB) += igb/
obj-$(CONFIG_IGB_NEW) += igb_new/
obj-$(CONFIG_IGBVF) += igbvf/
obj-$(CONFIG_I40E) += i40e/
obj-$(CONFIG_IXGBE) += ixgbe/
obj-$(CONFIG_IXGBE_NEW) += ixgbe_new/
obj-$(CONFIG_IXGBEVF) += ixgbevf/
obj-$(CONFIG_IXGB) += ixgb/
